export const PlanetInfo = [
  {
    name: 'sun',
    star: 'sunStar',
    radius: 100,
    color: '#FFF599',
    velocity: 0,
    orbitRadius: 0,
  },
  {
    name: 'mercury',
    star: 'sun',
    radius: 5,
    color: '#74B1E9',
    velocity: 0.002,
    orbitRadius: 120,
  },
  {
    name: 'venus',
    star: 'sun',
    radius: 12,
    color: '#F3E6B7',
    velocity: 0.003,
    orbitRadius: 150,
  },
  {
    name: 'earth',
    star: 'sun',
    radius: 14,
    color: '#AAE7F0',
    velocity: 0.004,
    orbitRadius: 170,
  },
  {
    name: 'moon',
    star: 'earth',
    radius: 4,
    color: '#F0F7F8',
    velocity: 0.01,
    orbitRadius: 28,
  },
  {
    name: 'mars',
    star: 'sun',
    radius: 6,
    color: '#F39999',
    velocity: 0.0035,
    orbitRadius: 200,
  },
  {
    name: 'jupiter',
    star: 'sun',
    radius: 32,
    color: '#B3D8A1',
    velocity: 0.001,
    orbitRadius: 260,
  },
  {
    name: 'saturn',
    star: 'sun',
    radius: 26,
    color: '#E3AE90',
    velocity: 0.0015,
    orbitRadius: 330,
  },
  {
    name: 'uranus',
    star: 'sun',
    radius: 20,
    color: '#8C7E75',
    velocity: 0.0025,
    orbitRadius: 380,
  },
  {
    name: 'neptune',
    star: 'sun',
    radius: 18,
    color: '#A888BB',
    velocity: 0.002,
    orbitRadius: 430,
  },
]