export const PlanetInfo = [
  {
    id: 0,
    name: 'sun',
    star: 'sunStar',
    radius: 80,
    color: '#FFF599',
    velocity: 0,
    orbitRadius: 0,
  },
  {
    id: 1,
    name: 'mercury',
    star: 'sun',
    radius: 5,
    color: '#74B1E9',
    velocity: 0.008,
    orbitRadius: 120,
  },
  {
    id: 2,
    name: 'venus',
    star: 'sun',
    radius: 11,
    color: '#F3E6B7',
    velocity: 0.005,
    orbitRadius: 142,
  },
  {
    id: 3,
    name: 'earth',
    star: 'sun',
    radius: 13,
    color: '#AAE7F0',
    velocity: 0.006,
    orbitRadius: 172,
  },
  {
    id: 4,
    name: 'moon',
    star: 'earth',
    radius: 4,
    color: '#F0F7F8',
    velocity: 0.02,
    orbitRadius: 28,
  },
  {
    id: 5,
    name: 'mars',
    star: 'sun',
    radius: 6,
    color: '#F39999',
    velocity: 0.007,
    orbitRadius: 219,
  },
  {
    id: 6,
    name: 'jupiter',
    star: 'sun',
    radius: 28,
    color: '#B3D8A1',
    velocity: 0.004,
    orbitRadius: 260,
  },
  {
    id: 7,
    name: 'saturn',
    star: 'sun',
    radius: 24,
    color: '#E3AE90',
    velocity: 0.0035,
    orbitRadius: 310,
  },
  {
    id: 8,
    name: 'uranus',
    star: 'sun',
    radius: 18,
    color: '#8C7E75',
    velocity: 0.003,
    orbitRadius: 357,
  },
  {
    id: 9,
    name: 'neptune',
    star: 'sun',
    radius: 16,
    color: '#A888BB',
    velocity: 0.002,
    orbitRadius: 396,
  },
];
